/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import cryptography.RSAAsymmetricCryptography;
import dao.UserAccountDAO;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.security.PrivateKey;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import pojo.UserAccount;

/**
 *
 * @author Skys
 */
public class DangNhapDlg extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapDlg
     */
    private UserAccount userAccount = null;
    private boolean isMovemouse = false;
    private PropertyChangeSupport _eVentDangNhapThanhCong = new PropertyChangeSupport(this);
    private PropertyChangeSupport _eVentExit = new PropertyChangeSupport(this);
    private java.awt.Frame parentthis;
    public DangNhapDlg(java.awt.Frame parent, boolean modal,UserAccount user) {
        super(parent, modal);
        contructorMain(parent);
        if(user!=null)
         jtxtAccount.setText(user.getMaUser());
        readXMLAccountLogin();
    }
    public void contructorMain(java.awt.Frame parent){
        initComponents();
        this.setLocationRelativeTo(null);
        jlbThongBao.setText("");
        parentthis = parent;
    }
    public void addClientDangNhapThanhCongEvent(PropertyChangeListener lsn){
        _eVentDangNhapThanhCong.addPropertyChangeListener(lsn);
    }
    public void removeClientDangNhapThanhCongEvent(PropertyChangeListener lsn){
        _eVentDangNhapThanhCong.removePropertyChangeListener(lsn);
    }
    public void addClientExitEvent(PropertyChangeListener lsn){
        _eVentExit.addPropertyChangeListener(lsn);
    }
    public void removeClientExitEvent(PropertyChangeListener lsn){
        _eVentExit.removePropertyChangeListener(lsn);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtAccount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jlbThongBao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connect");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Đăng nhập");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/486.png"))); // NOI18N

        jLabel4.setText("Account:");

        jLabel5.setText("Passord:");

        jtxtAccount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtAccountMouseClicked(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtAccount)
                    .addComponent(jtxtPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quên mật khẩu");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });

        jlbThongBao.setForeground(new java.awt.Color(255, 0, 0));
        jlbThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongBao.setText("Đăng nhập thất bại!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jlbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setExitEvent();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void setExitEvent(){
        _eVentExit.firePropertyChange(null, null, null);
    }
    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        // TODO add your handling code here:
        if(!isMovemouse){
         jLabel6.setBorder(BorderFactory.createLineBorder(new Color(0, 51, 153)));
         //jLabel6.setForeground(Color.RED);
         isMovemouse = true;
        }
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        if(isMovemouse){
            isMovemouse = false;
            jLabel6.setBorder(null);
            jLabel6.setForeground(new Color(0, 51, 153));
        }
    }//GEN-LAST:event_jLabel6MouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setExitEvent();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jtxtPassword.getText().trim().isEmpty()){
            jlbThongBao.setText("Đăng nhập thất bại!!!");
            return;
        }
        userAccount = UserAccountDAO.layThongTinUser(jtxtAccount.getText().toUpperCase());
        //List<UserAccount> lst = UserAccountDAO.layDanhSachUser();
        if(userAccount==null){
            jlbThongBao.setText("Đăng nhập thất bại!!!");
        }else{
            if(userAccount.getMatKhau().trim().equals(jtxtPassword.getText().trim())){
            jlbThongBao.setText("");
            _eVentDangNhapThanhCong.firePropertyChange(null,null,userAccount);
            this.dispose();
            } else
                jlbThongBao.setText("Đăng nhập thất bại!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtAccountMouseClicked
        // TODO add your handling code here:
        jlbThongBao.setText("");
    }//GEN-LAST:event_jtxtAccountMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        ForgotPassworDlg forgotpw = new ForgotPassworDlg(parentthis, true);
        
        //Su kien nguoi dung lay lai mat khau thanh cong: Tu dien Account + Pass cho ngươi dung
        forgotpw.addClientLayLaiMatKhauThanhCongEvent(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                actionLogin((UserAccount)evt.getNewValue());
            }
        });
        forgotpw.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

   
    private void actionLogin(UserAccount user){
        jtxtAccount.setText(user.getMaUser());
        jtxtPassword.setText(user.getMatKhau());
    }
   private void readXMLAccountLogin(){
       //Gia ma Ma hoa bat doi xung
       new Thread(new Runnable() {

           @Override
           public void run() {
             PrivateKey privateKey = RSAAsymmetricCryptography.getPrivateKey("key.private");
             String strAccount =RSAAsymmetricCryptography.decryptData(privateKey,"key.account");
               jtxtAccount.setText(strAccount);
           }
       }).start();
       //JOptionPane.showMessageDialog(parentthis, strAccount);
       
       /*
       try{
        Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse("inforlogin.xml");
        NodeList nodeL = doc.getElementsByTagName("account");
        String strEncyptData = nodeL.item(0).getTextContent().trim();
           JOptionPane.showMessageDialog(parentthis, strEncyptData);
        //jtxtAccount.setText(strEncyptData);
    }catch(Exception ex){
       jtxtAccount.setText("");
        return;
    }
    */
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapDlg dialog = new DangNhapDlg(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbThongBao;
    private javax.swing.JTextField jtxtAccount;
    private javax.swing.JPasswordField jtxtPassword;
    // End of variables declaration//GEN-END:variables
}
