/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import cryptography.RSAAsymmetricCryptography;
import java.awt.Frame;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import pojo.UserAccount;

/**
 *
 * @author Skys
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private UserAccount user_account;
    private Socket _socketClient;
    private boolean _bStopConnect = false;
    private BufferedWriter writer;
    private BufferedReader reader;
    private String strTitle = "Quản Lý Siêu Thị";
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void addTextChat(String strName,String strMess){
     jtxtfChat.append(strName + ": ");
     jtxtfChat.append(strMess);
     jtxtfChat.append("\n");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JSeparator();
        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtfChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton15 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMnManager = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem15.setText("jMenuItem15");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Siêu Thị");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Quản Lý Siêu Thị"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đồ Án Cuối Kỳ - Môn Java");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Siêu Thị"));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hoadonbanhang.png"))); // NOI18N
        jButton3.setToolTipText("Lập Phiếu Bán Hàng");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/phieunhaphang.png"))); // NOI18N
        jButton2.setToolTipText("Lập Phiếu Nhập Hàng");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/phieuxuathang.png"))); // NOI18N
        jButton1.setToolTipText("Lập Phiếu Xuất Hàng");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khuyenmai.png"))); // NOI18N
        jButton4.setToolTipText("Chương Trình Khuyến Mãi");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khachhangthanthiet.png"))); // NOI18N
        jButton5.setToolTipText("Khách Hàng Thân Thiết");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Báo Cáo"));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tonkho.png"))); // NOI18N
        jButton6.setToolTipText("Lập Báo Cáo Tồn Kho");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/doanhthu.png"))); // NOI18N
        jButton7.setToolTipText("Lập Báo Cáo Doanh Thu");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loinhuan.png"))); // NOI18N
        jButton8.setToolTipText("Lập Báo Cáo Lợi Nhuận");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Manager"));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quanlynhanvien.png"))); // NOI18N
        jButton9.setToolTipText("Quản Lý Nhân Viên");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khuyenmai.png"))); // NOI18N
        jButton10.setToolTipText("Chương Trình Khuyến Mãi");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quidinh.png"))); // NOI18N
        jButton11.setToolTipText("Quản Lý Qui Định");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mathang.png"))); // NOI18N
        jButton12.setToolTipText("Quản Lý Mặt Hàng");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khachhangthanthiet.png"))); // NOI18N
        jButton13.setToolTipText("Khách Hàng Thân Thiết");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton9)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConnect.setText("Connect");
        btnConnect.setToolTipText("");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Phòng Chat Siêu Thị"));

        jtxtfChat.setColumns(20);
        jtxtfChat.setRows(5);
        jScrollPane1.setViewportView(jtxtfChat);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jButton15.setText("Send");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/use1.png"))); // NOI18N
        jMenu1.setText("User");
        jMenu1.setToolTipText("");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItem4.setText("Thông tin người dùng");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator4);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/key.png"))); // NOI18N
        jMenuItem8.setText("Đổi mật khẩu");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator1);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit.png"))); // NOI18N
        jMenuItem6.setText("Đăng xuất");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator5);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dangxuat.png"))); // NOI18N
        jMenuItem9.setText("Đóng ứng dụng");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sieuthi.png"))); // NOI18N
        jMenu4.setText("Siêu Thị");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/phieunhaphang.png"))); // NOI18N
        jMenuItem10.setText("Lập Phiếu Nhập Hàng");
        jMenu4.add(jMenuItem10);
        jMenu4.add(jSeparator10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/phieuxuathang.png"))); // NOI18N
        jMenuItem11.setText("Lập Phiếu Xuất Hàng");
        jMenu4.add(jMenuItem11);
        jMenu4.add(jSeparator8);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hoadonbanhang.png"))); // NOI18N
        jMenuItem12.setText("Lập Hóa Đơn Bán Hàng");
        jMenu4.add(jMenuItem12);
        jMenu4.add(jSeparator7);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khuyenmai.png"))); // NOI18N
        jMenuItem13.setText("Chương Trình Khuyến Mãi");
        jMenu4.add(jMenuItem13);
        jMenu4.add(jSeparator6);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khachhangthanthiet.png"))); // NOI18N
        jMenuItem14.setText("Khách Hàng Thân Thiết");
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/baocao.png"))); // NOI18N
        jMenu5.setText("Báo Cáo");

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tonkho.png"))); // NOI18N
        jMenuItem16.setText("Lập Báo Cáo Tồn Kho");
        jMenuItem16.setToolTipText("");
        jMenu5.add(jMenuItem16);
        jMenu5.add(jSeparator12);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/doanhthu.png"))); // NOI18N
        jMenuItem17.setText("Lập Báo Cáo Doanh Thu");
        jMenu5.add(jMenuItem17);
        jMenu5.add(jSeparator11);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/loinhuan.png"))); // NOI18N
        jMenuItem18.setText("Lập Báo Cáo Lợi Nhuận");
        jMenu5.add(jMenuItem18);

        jMenuBar1.add(jMenu5);

        jMnManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/manager.png"))); // NOI18N
        jMnManager.setText("Manager");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quanlynhanvien.png"))); // NOI18N
        jMenuItem5.setText("Quản Lý Nhân Viên");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMnManager.add(jMenuItem5);
        jMnManager.add(jSeparator16);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mathang.png"))); // NOI18N
        jMenuItem19.setText("Quản Lý Mặt Hàng");
        jMnManager.add(jMenuItem19);
        jMnManager.add(jSeparator15);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khachhangthanthiet.png"))); // NOI18N
        jMenuItem21.setText("Khách Hàng Thân Thiết");
        jMnManager.add(jMenuItem21);
        jMnManager.add(jSeparator14);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khuyenmai.png"))); // NOI18N
        jMenuItem20.setText("Chương Trình Khuyến Mãi");
        jMnManager.add(jMenuItem20);
        jMnManager.add(jSeparator13);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/quidinh.png"))); // NOI18N
        jMenuItem22.setText("Quản Lý Qui Định");
        jMnManager.add(jMenuItem22);

        jMenuBar1.add(jMnManager);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/network.png"))); // NOI18N
        jMenu6.setText("Network");

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chat.png"))); // NOI18N
        jMenuItem23.setText("Chat");
        jMenu6.add(jMenuItem23);
        jMenu6.add(jSeparator18);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/optionnetwork.png"))); // NOI18N
        jMenuItem24.setText("Options Connect");
        jMenu6.add(jMenuItem24);

        jMenuBar1.add(jMenu6);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help.png"))); // NOI18N
        jMenu8.setText("Help");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/about.png"))); // NOI18N
        jMenuItem2.setText("Hướng dẫn");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem2);
        jMenu8.add(jSeparator2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/IconAbout.png"))); // NOI18N
        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConnect))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 232, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConnect)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AboutJDlg f = new AboutJDlg(this, true);
        f.setVisible(true);
  
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DangNhapDlg dnhap = new DangNhapDlg(this, true,null);
        
        //Su kien Exit o ben Frame dang nhap-MainFrame cung exit theo.
        dnhap.addClientExitEvent(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                closeWindows();
            }
        });
        
        //Su kien dang nhao thanh cong
        dnhap.addClientDangNhapThanhCongEvent(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                actionUserLoginSuccess((UserAccount)evt.getNewValue());
            }
        });
        dnhap.setVisible(true);
        
    }//GEN-LAST:event_formWindowOpened

    private void updateFormSuccess(UserAccount user){
        user_account = user;
        this.setTitle( strTitle+ "-" + user_account.getMaUser());
    }
    private void actionUserLoginSuccess(UserAccount user){
        updateFormSuccess(user);
        //Neu la admin hoac moderator thi co the su dung Nhom' menu Manager
        switch(user.getTypeLoginUser()){
            case "A":
            case "M":
                jMnManager.setEnabled(true);
                break;
            case "N":
                jMnManager.setEnabled(false);
                break;
        }
    }
    private void closeWindows(){
        this.dispose();
    }
    private void dangnhapUngDung(UserAccount user){
        DangNhapDlg dnhap = new DangNhapDlg(this, true,user);
        
        //Su kien Exit o ben Frame dang nhap-MainFrame cung exit theo.
        dnhap.addClientExitEvent(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                closeWindows();
            }
        });
        
        //Su kien dang nhao thanh cong
        dnhap.addClientDangNhapThanhCongEvent(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                actionUserLoginSuccess((UserAccount)evt.getNewValue());
            }
        });
        dnhap.setVisible(true);
    }
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        createXMLAccountLogin();
        dangnhapUngDung(user_account);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //Mo file huong dan hoac ghi huong dan tren Panel chuong trinh
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        UserAccountDlg userdlg = new UserAccountDlg(this, true,user_account);
        userdlg.setVisible(true);
        //JOptionPane.showMessageDialog(null, user_account.getDiaChiUser());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ChangePasswordDlg doimatkhau = new ChangePasswordDlg(this, true, user_account);
        doimatkhau.addDoiMatKhauThanhCongEvent(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                actionUserLoginSuccess((UserAccount)evt.getNewValue());
            }
        });
                
        doimatkhau.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        createXMLAccountLogin();
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        if(btnConnect.getText().compareTo("Connect")==0){
         _bStopConnect = false;
         btnConnect.setText("Stop");
         //txtIp.setEditable(false);
         //txtPort.setEnabled(false);
         //txtNickName.setEditable(false);
       try{
       _socketClient = new Socket(/*txtIp.getText()*/"127.0.0.1",Integer.parseInt(/*txtPort.getText()*/"2014"));
       writer = new BufferedWriter(new OutputStreamWriter(_socketClient.getOutputStream()));
       reader = new BufferedReader(new InputStreamReader(_socketClient.getInputStream()));
       writer.write(/*user_account.getTenUser()*/"Demo"); writer.newLine();
       writer.flush();
       if(!reader.readLine().equals("Ok")){
           addTextChat("Máy tính", "Kết nối thất bại");
       }
       else{
          addTextChat("Máy tính", "Kết nối thành công.");
                    Thread t = new Thread(new Runnable() {

                    public void run() {
                        String strDemo = "";
                        while(true){
                            if(_bStopConnect) return;
                            try{
                             strDemo = reader.readLine();
                            if(strDemo.equals("-Exit-")){
                                reader.readLine();
                                addTextChat("Máy tính", "Máy chủ đã thoát!");
                                _bStopConnect = true;
                                return;
                            }
                            if(!strDemo.equals("Demo"))
                            addTextChat(strDemo, reader.readLine());
                            else{
                                 reader.readLine();
                                 continue;
                            }
                            }catch(Exception ex){
                                
                            }
                            
                        }
                    }
                });
       t.start();
       }
       }catch(Exception ex){
       }
       return;
     }
     if(btnConnect.getText().compareTo("Stop")==0){
        //txtIp.setEditable(true);
        //txtPort.setEnabled(true);
        //txtNickName.setEditable(true);
       try{
           writer.write("-Exit-" + "\n");
           writer.flush();
           _socketClient.close();
       }catch(Exception ex){
           
       }
       btnConnect.setText("Connect");
       addTextChat("Máy tính","Bạn đã thoát.");
       return;
     }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        createXMLAccountLogin();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        NhanVienSieuThiDlg nhanvienDlg = new NhanVienSieuThiDlg(this, true, user_account,false);
        nhanvienDlg.addCapNhatThanhCongCongEvent(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                updateFormSuccess((UserAccount)evt.getNewValue());
            }
        });
        nhanvienDlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    private void createXMLAccountLogin(){
     //Save Ma hoa bat doi xung
     KeyPair keyPair = RSAAsymmetricCryptography.generateKeyPair(512);
     PublicKey pubKey = RSAAsymmetricCryptography.savePublicKey("key.public", keyPair);
     PrivateKey privateKey = RSAAsymmetricCryptography.savePrivateKey("key.private", keyPair);
     RSAAsymmetricCryptography.encryptData(user_account.getMaUser(), pubKey, "key.account");
     /*
    try{
    Document doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().newDocument();
    Element root =  doc.createElement("saveinfologin");
    doc.appendChild(root);
    
    //Tao chu thich
    doc.appendChild(doc.createComment(" Thong tin dang nhap"));
    
    Element account = doc.createElement("account");
    root.appendChild(account);
    if(user_account==null)
       account.appendChild(doc.createTextNode(""));
    else
       account.appendChild(doc.createTextNode(user_account.getMaUser()));
    

    Transformer trans = TransformerFactory.newInstance().newTransformer();
    
    // Hien hoac ko hien dong <?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
    // Neu run thi hien
    // trans.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION,"yes");
    
    trans.setOutputProperty(OutputKeys.METHOD,"xml");
    trans.setOutputProperty(OutputKeys.ENCODING,"ISO-8859-1");
    trans.setOutputProperty(OutputKeys.STANDALONE, "yes");
    trans.setOutputProperty(OutputKeys.INDENT, "yes");
    trans.transform(new DOMSource(doc), new StreamResult(new File("inforlogin.xml")));
    }catch(Exception ex){
        return;
    }
    */
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMnManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jtxtfChat;
    // End of variables declaration//GEN-END:variables
}
