/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Skys
 */
public class ServerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ServerJFrame
     */
    private ServerSocket _serverSocket;
    private boolean _bStopListen = false;
    public static ClientData _clients = new ClientData();
    public ServerJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void addTextChat(String strName,String strMess){
    jtxtaChat.append(strName + ": ");
    jtxtaChat.append(strMess);
    jtxtaChat.append("\n");
    _clients.sendMessage(strName, strMess);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaChat = new javax.swing.JTextArea();
        txtIp = new javax.swing.JTextField();
        btnListen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnStop = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        lbMembers = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Server");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Chat Siêu Thị");

        jtxtaChat.setColumns(20);
        jtxtaChat.setLineWrap(true);
        jtxtaChat.setRows(5);
        jtxtaChat.setBorder(javax.swing.BorderFactory.createTitledBorder("Nội dung Client Chat"));
        jtxtaChat.setFocusable(false);
        jScrollPane1.setViewportView(jtxtaChat);

        txtIp.setEditable(false);
        txtIp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIp.setForeground(new java.awt.Color(0, 51, 153));
        txtIp.setText("127.0.0.1");

        btnListen.setText("Listen");
        btnListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("IP:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Port:");

        txtPort.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPort.setForeground(new java.awt.Color(0, 51, 153));
        txtPort.setText("2014");

        btnStop.setText("Stop");
        btnStop.setEnabled(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lbStatus.setForeground(new java.awt.Color(255, 0, 0));
        lbStatus.setText("Status: Idle");

        lbMembers.setForeground(new java.awt.Color(0, 51, 153));
        lbMembers.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMembers.setText("Members: 10");
        lbMembers.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnListen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStatus)
                    .addComponent(lbMembers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListen)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListenActionPerformed
        // TODO add your handling code here:
        
    _bStopListen = false;
    btnListen.setText("Listening");
    btnListen.setEnabled(false);
    btnStop.setEnabled(true);
    lbStatus.setText("Status: Open");
    txtPort.setEditable(false);
    Thread tAction = new Thread(new Runnable() {

            public void run() {
                try{
                    _serverSocket = new ServerSocket(Integer.parseInt(txtPort.getText()));
                    addTextChat("Máy tính","Máy chủ đã hoạt động ... ");
                }catch(Exception ex){
                    addTextChat("Máy tính","Máy chủ gặp sự cố- ngừng hoạt động ... ");
                }
               while(true){
                   if(_bStopListen) return;
                   try{
                   Socket s = _serverSocket.accept();
                   BufferedReader reader = new BufferedReader(new InputStreamReader(s.getInputStream()));
                   BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(s.getOutputStream()));
                   String strName = reader.readLine();
                   writer.write("Ok");
                   writer.newLine();
                   writer.flush();
                   _clients.addSocket(s,strName);
                   JOptionPane.showMessageDialog(null, strName);
                   addTextChat(strName,"Đã tham gia nhóm chat ...");
                   AcceptClient client = new AcceptClient(s,strName);
                   client.addClientSendMessEvent(new PropertyChangeListener() {

                                public void propertyChange(PropertyChangeEvent evt) {
                                   addTextChat(evt.getPropertyName(), evt.getNewValue().toString());
                                }
                            });
                   client.addClientExitEvent(new PropertyChangeListener() {

                                public void propertyChange(PropertyChangeEvent evt) {
                                   _clients.removeSocket(evt.getPropertyName());
                                   addTextChat("Server",evt.getPropertyName() + " đã thoát.");
                                }
                            });
                   }catch(Exception ex){
                        //addTextChat("Server",ex.getMessage());
                   }
               }
            }
        });
    tAction.start();
    return;
    }//GEN-LAST:event_btnListenActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
       addTextChat("Máy tính","Máy chủ đã ngưng hoạt động ... ");
       btnListen.setText("Listen");
       txtPort.setEditable(true);
       btnListen.setEnabled(true);
       btnStop.setEnabled(false);
       lbStatus.setText("Status: Idle");
       try{
           _clients.sendMessage("-Exit-","Exit");
           _serverSocket.close();
       }catch(Exception ex){
           
       }
       _clients.removeAll();
       _bStopListen = true;
       btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListen;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtaChat;
    private javax.swing.JLabel lbMembers;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
